/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OverflowMenu {
    }
}
declare global {
    interface HTMLOverflowMenuElement extends Components.OverflowMenu, HTMLStencilElement {
    }
    var HTMLOverflowMenuElement: {
        prototype: HTMLOverflowMenuElement;
        new (): HTMLOverflowMenuElement;
    };
    interface HTMLElementTagNameMap {
        "overflow-menu": HTMLOverflowMenuElement;
    }
}
declare namespace LocalJSX {
    interface OverflowMenu {
    }
    interface IntrinsicElements {
        "overflow-menu": OverflowMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "overflow-menu": LocalJSX.OverflowMenu & JSXBase.HTMLAttributes<HTMLOverflowMenuElement>;
        }
    }
}
